spring:
  application:
    namspring:
      application:
        name: ms-venta-service
      profiles:
        active: development
      config:
        ime: ms-venta-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:7070